use_frameworks!

platform :ios, '8.0'

target 'GFMagicUI_Example' do
  pod 'GFMagicUI', :path => '../'

  target 'GFMagicUI_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
